### ISSUE TITLE
Not Working to Post to Todoist

### ISSUE THREAD

**Issue by kitsully** [moranje/alfred-workflow-todoist#8]
Hi,

This workflow isn't working for me after inserting my token. I get the success popup, but nothing shows up in todoist.

Thank!

**Comment by moranje** [comment]
Try this one:

[Fix](https://github.com/moranje/alfred-workflow-todoist/raw/master/dist/Alfred%20Workflow%20Todoist.alfredworkflow)

**Comment by kitsully** [comment]
No luck. I'm supposed to add the token by running the t:token command and pasting it in right?

**Comment by moranje** [comment]
Yes, there should be a file called settings.json in ~/Library/Application
Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist. ~ stands for
you home directory (/Users/{username}). Can you verify that it’s there?


-- 
Martien Oranje

Op 26 augustus 2016 bij 23:13:05, Kristopher Sullivan (
notifications@github.com) schreef:

No luck. I'm supposed to add the token by running the t:token command and
pasting it in right?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/moranje/alfred-workflow-todoist/issues/8#issuecomment-242853118>,
or mute the thread

**Comment by kitsully** [comment]
It is there. Looks like it has my token in it too.

**Comment by moranje** [comment]
Okay, so you did replace the workflow with the one I send you? You haven't changed any of the commands right? Can you send me the exact command you used to create a task?

Here's a couple of things I need you to check:
- Is there a file called todoist.json here `~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.alfred-workflow-todoist`
- Does it have any data in it?

**Comment by moranje** [comment]
I have a better idea, I baked you a version with some more debug information baked in. Do you know how to open the debug console in Alfred? Send me the debug information that this version spits out when you run `todo test`.

DEBUG VERSION 3.1.2
[Alfred Workflow Todoist](https://dl.dropboxusercontent.com/u/10112105/Alfred%20Workflow%20Todoist.alfredworkflow)

**Comment by moranje** [comment]
Should be fixed now, #9 thanks @WillPlatnick

**Comment by kitsully** [comment]
It seems like its working now. I think this is all my bad. I had a weird NodeJS configuration. Thanks for all your help though. I really appreciate it.
